version: '2'
services:
  solr:
    build: ./solr
    stdin_open: true
    tty: true
    labels:
      name: ckan-solr
      io.rancher.container.pull_image: always
  ckan:
    build: ./ckan
    environment:
      CKAN_SITE_URL: http://localhost:5000
      CKAN_INI_PATH: /etc/ckan/default/ckan.ini
      CKAN_SQLALCHEMY_URL: postgresql://ckan:ckan@db:5432/
      CKAN_REDIS_URL: redis://redis:6379/
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
    stdin_open: true
    entrypoint:
    - /wait-for-services.sh
    - /ckan-entrypoint.sh
    tty: true
    links:
    - db:db
    - redis:redis
    - solr:solr
    ports:
    - 5000:5000/tcp
    command:
    - paster
    - serve
    - /etc/ckan/default/ckan.ini
    labels:
      name: ckan-core
      io.rancher.container.pull_image: always
  redis:
    image: redis:5.0.5
    stdin_open: true
    tty: true
  db:
    image: ckan/postgresql:latest
    stdin_open: true
    tty: true
